version: '3.8'

services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile.websocket  
    ports:
      - "8081:8081" 
    environment:
      - WS_PORT=8081 
    

  latency-check:
    build:
      context: .
      dockerfile: Dockerfile.latency  
    depends_on:
      - websocket-server 
    environment:
      - WS_SERVER=websocket-server 
      - WS_PORT=8081
      - TARGET_WEBSITE=0.0.0.0:80

